### ISSUE TITLE
feature request: expose client api

### ISSUE THREAD

**Issue by devsnek** [hugmanrique/turbo-ws#4]
i'm really enjoying using this, it would be nice if we could create websocket clients too

**Comment by hugmanrique** [comment]
Unfortunately the `turbo-http` library currently only has the server implementation. If they ever add an HTTP client we could reconsider adding this.

**Comment by jacktuck** [comment]
Maybe a `turbo-ws-client` library would make more sense? :)

**Comment by hugmanrique** [comment]
Still, the main feature of this project is that it uses the turbo-http library, and if the base on which this package is built doesn't support them yet imo there's no "good" way to do it other than going for a replacement which works such as the `ws` library.
