### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by lpinca** [hugmanrique/turbo-ws#7]
A **lot** of the current code in this repository has been copied and pasted from `ws`.

| turbo-ws | ws|
|-----------|----|
| https://github.com/hugmanrique/turbo-ws/blob/9b42d136877603e63468d1a9d0ab5fc69c67adab/src/validate.js| https://github.com/websockets/ws/blob/9dc25a380d003142aad9bf1bbfce6fa5d1b5e81c/lib/validation.js|
|https://github.com/hugmanrique/turbo-ws/blob/9b42d136877603e63468d1a9d0ab5fc69c67adab/src/socket/Receiver.js|https://github.com/websockets/ws/blob/9dc25a380d003142aad9bf1bbfce6fa5d1b5e81c/lib/receiver.js|
| https://github.com/hugmanrique/turbo-ws/blob/9b42d136877603e63468d1a9d0ab5fc69c67adab/src/socket/Sender.js| https://github.com/websockets/ws/blob/9dc25a380d003142aad9bf1bbfce6fa5d1b5e81c/lib/sender.js|
| https://github.com/hugmanrique/turbo-ws/blob/9b42d136877603e63468d1a9d0ab5fc69c67adab/src/socket/index.js| https://github.com/websockets/ws/blob/9dc25a380d003142aad9bf1bbfce6fa5d1b5e81c/lib/websocket.js|

And probably more. The MIT license has only 1 condition

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Please respect it.

**Comment by hugmanrique** [comment]
I'm aware of me copying most parts of your project, and I love it! I didn't want to reinvent the wheel by implementing an entire WebSocket lib for a specific net lib, so I used some parts of yours.

I'm sorry I forgot to change the README file before pushing these commits (as I'm not done with it yet). Will do right now!

**Comment by hugmanrique** [comment]
Fixed in 4ead69c73a684b1e77986fe80db59fac98ff0ff3
